#!/usr/bin/env python3
import sys
sys.path.append('./model')
from directModel import *
import korali

import shutil
import os
if( os.path.exists("./_korali_result/") ) :
  shutil.rmtree("./_korali_result/")


k = korali.Engine()

k["Problem"] = "Direct Evaluation"

k.setModel( evaluateModel )

k["Variables"][0]["Name"] = "X"
k["Variables"][0]["MCMC"]["Initial Mean"] = 0.0;
k["Variables"][0]["MCMC"]["Initial Standard Deviation"] = 1.000;

k["Solver"] = "MCMC";
k["MCMC"]["Population Size"] = 5000;
k["MCMC"]["Burn In"] = 500;
k["MCMC"]["Adaptive Sampling"]  = True;
k["MCMC"]["Result Output Frequency"] = 1e5

k.run()
