#!/usr/bin/env python3
import sys
sys.path.append('./model')
from posteriorModel import *
import korali

k = korali.Engine()
x, y = getReferenceData()

k["Seed"] = 0xC0FFEE;
k["Verbosity"] = "Detailed";
k["Problem"]["Evaluation Type"] = "Bayesian";

k["Problem"]["Variables"][0]["Name"] = "a";
k["Problem"]["Variables"][0]["Type"] = "Computational";
k["Problem"]["Variables"][0]["Prior Distribution"]["Type"] = "Uniform";
k["Problem"]["Variables"][0]["Prior Distribution"]["Minimum"] = -5.0;
k["Problem"]["Variables"][0]["Prior Distribution"]["Maximum"] = +5.0;

k["Problem"]["Variables"][1]["Name"] = "b";
k["Problem"]["Variables"][1]["Type"] = "Computational";
k["Problem"]["Variables"][1]["Prior Distribution"]["Type"] = "Uniform";
k["Problem"]["Variables"][1]["Prior Distribution"]["Minimum"] = -5.0;
k["Problem"]["Variables"][1]["Prior Distribution"]["Maximum"] = +5.0;

k["Problem"]["Variables"][2]["Name"] = "Sigma";
k["Problem"]["Variables"][2]["Type"] = "Statistical";
k["Problem"]["Variables"][2]["Prior Distribution"]["Type"] = "Uniform";
k["Problem"]["Variables"][2]["Prior Distribution"]["Minimum"] = 0.0;
k["Problem"]["Variables"][2]["Prior Distribution"]["Maximum"] = 10.0;

k["Problem"]["Reference Data"] = y;

k["Solver"]["Method"] = "CMA-ES";

k["Solver"]["Initial Means"][0] = 10.0;
k["Solver"]["Initial Means"][1] = 10.0;
k["Solver"]["Initial Means"][2] = 10.0;

k["Solver"]["Initial Standard Deviations"][0] = 1.0;
k["Solver"]["Initial Standard Deviations"][1] = 1.0;
k["Solver"]["Initial Standard Deviations"][2] = 1.0;
 
k["Solver"]["Sample Count"] = 10;
k["Solver"]["Termination Criteria"]["Min DeltaX"]["Value"]= 1e-6;
k["Solver"]["Termination Criteria"]["Max Generations"]["Value"] = 1e4;
k["Solver"]["Termination Criteria"]["Max Model Evaluations"]["Value"] = 3e5;

k.setModel(lambda koraliData: evaluateModel(koraliData, x))

k.run()
