#!/bin/bash

logFile=$PWD/install.log
echo "" > $logFile

# Help display function
function print_help ()
{
 echo ""
 echo "Syntax: ./install"
 echo "        [--prereqs]"
 echo "        [--rebuild]"
 echo "        [--debug]"
 echo "        [--jobs=N]"
 echo "        [--help]"
 echo ""
 echo "Where:"
 echo " --prereqs Allows Korali to install any missing prerequisites."
 echo " --rebuild Cleans and rebuilds/installs Korali for development purposes."
 echo " --debug builds a non-optimized Korali for debugging purposes."
 echo " --jobs=N Specifies N jobs to use when building Korali."
 echo " --help Displays this help message."
}

# Logging and printing function.
function logEcho ()
{
 echo "$1"
 echo "$1" >> $logFile
}

# Logging function.
function log ()
{
 echo "$1" >> $logFile
}

# Exit with error message.
function exitWithError ()
{
 >&2 echo "[Korali] Installation Error: Check $logFile for more information."
 exit -1
}

function check()
{
 if [ ! $? -eq 0 ]
 then
  exitWithError
 fi 
}

INSTALLREQS=0
NJOBS=4
OPTFLAGS="-O3"

for i in "$@"
do
case $i in
    --prereqs)
    INSTALLREQS=1
    shift 
    ;;
    --debug)
    OPTFLAGS="-O0"
    shift 
    ;;
    --jobs=*)
    NJOBS="${i#*=}"
    shift
    ;;
    --rebuild)
    logEcho "[Korali] Cleaning Korali for new build..."
    python3 -m pip uninstall -y korali >> $logFile 2>&1
    make -C source clean >> $logFile 2>&1
    make -C external/libco clean >> $logFile 2>&1
    shift 
    ;;
    --help)
    print_help
    exit 0 
    shift 
    ;;
    *)
    print_help
    echo ""
    echo "[Korali] Error:  Unknown option $i."       
    exit 1
    ;;
esac
done

######### Environment Configuration ########

baseKoraliDir=$PWD
foundbinVersionFile=0

if [ -f $baseKoraliDir/docs/VERSION ]; then
 foundbinVersionFile=1
fi

if [ $foundbinVersionFile == 0 ]; then
  echo "[Korali] Error: You need to run this file from Korali's base folder."
  exit 1
fi

######## Start Configuration ######

version=`cat docs/VERSION`
logEcho "[Korali] Installing Korali v${version}..." 
logEcho "[Korali] Determining Configuration..." 
logEcho "[Korali] Using $NJOBS jobs."
log "[Korali] Checking for architecture..."
arch="$(uname -s)"

# Linux Architecture is default
SHAREDLIB_FLAG="-shared"

if [ "$arch" == "Linux" ]; then
 log "[Korali] Linux System Detected."
fi

# If using MacOs, change flags 
if [ "$arch" == "Darwin" ]; then
 log "[Korali] MacOS (Darwin) System Detected."
 SHAREDLIB_FLAG="-dynamiclib"
fi

######## Checking Compiler ########

logEcho "[Korali] Checking Pre-requisites..."

log "[Korali] Checking for C++ Compiler..."

$CXX --version > /dev/null 2>&1
DETECTED_CXX=$?
c++ --version > /dev/null 2>&1
DETECTED_CPLUSPLUS=$?
g++ --version > /dev/null 2>&1
DETECTED_GXX=$?
clang++ --version > /dev/null 2>&1
DETECTED_CLANG=$?
icpc --version > /dev/null 2>&1
DETECTED_ICPC=$?
CC --help > /dev/null 2>&1
DETECTED_CRAY=$?

USE_CXX=""
if [ $DETECTED_CPLUSPLUS -eq 0 ]; then USE_CXX=c++;     fi;
if [ $DETECTED_GXX       -eq 0 ]; then USE_CXX=g++;     fi;
if [ $DETECTED_ICPC      -eq 0 ]; then USE_CXX=icpc;    fi;
if [ $DETECTED_CRAY      -eq 0 ]; then USE_CXX=CC;      fi;
if [ $DETECTED_CLANG     -eq 0 ]; then USE_CXX=clang++; fi;
if [ $DETECTED_CXX       -eq 0 ]; then USE_CXX=$CXX;    fi;

######## Updating submodules ##########

logEcho "[Korali] Updating submodules..."
git submodule init >> $logFile 2>&1; check
git submodule update --remote >> $logFile 2>&1; check

######## Checking for Prerequisites ########

installFlag=
if [ $INSTALLREQS -eq 0 ]; then
 installFlag='--no-install'
fi


## Looking for CMake

./external/install_CMake.sh $installFlag --jobs=$NJOBS
if [ ! $? == 0 ]; then
 logEcho "[Korali] Error: CMake not found or older version than 3.0. Solutions:"
 logEcho "         . Have 'cmake' version >3.0 correctly installed and in your PATH environment variable"
 logEcho "         . Run './install --prereqs' to allow Korali install missing prerequisites automatically."
 exitWithError
fi

## Looking for libco
CXX=$USE_CXX ./external/install_libco.sh $installFlag --jobs=$NJOBS
if [ ! $? == 0 ]; then
 logEcho "[Korali] Error: Libco not found. Solutions"
 logEcho "         . Run './install --prereqs' to allow Korali install missing prerequisites automatically."
 exitWithError
fi

## Looking for Eigen
CXX=$USE_CXX ./external/install_eigen.sh $installFlag --jobs=$NJOBS
if [ ! $? == 0 ]; then
 logEcho "[Korali] Error: Eigen not found. Solutions"
 logEcho "         . Run './install --prereqs' to allow Korali install missing prerequisites automatically."
 exitWithError
fi

## Looking for GSL
CXX=$USE_CXX ./external/install_gsl.sh $installFlag --jobs=$NJOBS
if [ ! $? == 0 ]; then
 logEcho "[Korali] Error: GSL not found or older version than 2.5. Solutions"
 logEcho "         . Have 'gsl-config' version >2.5 correctly installed and in your PATH environment variable"
 logEcho "         . Run './install --prereqs' to allow Korali install missing prerequisites automatically."
 exitWithError
fi

## Looking for libGP
CXX=$USE_CXX ./external/install_libGP.sh $installFlag --jobs=$NJOBS
if [ ! $? == 0 ]; then
 logEcho "[Korali] libGP not found. Try either of these solutions:"
 logEcho "         . Run './install --prereqs' to allow Korali install missing prerequisites automatically."
 exitWithError
fi

## Looking for oneDNN
CXX=$USE_CXX ./external/install_oneDNN.sh $installFlag --jobs=$NJOBS
if [ ! $? == 0 ]; then
 logEcho "[Korali] oneDNN not found. Try either of these solutions:"
 logEcho "         1. Define the \$DNNLROOT environment variable to indicate the installation folder of oneDNN."
 logEcho "         2. Run './install --prereqs' to allow Korali install missing prerequisites automatically."
 exitWithError
fi

######## Checking support for MPI ########

MPIFLAGS=""
log "[Korali] Checking for MPI support..."
log "[Korali] Running \"\$MPICXX --help\"..."
$MPICXX --help > /dev/null 2>&1

if [ ! $? -eq 0 ]
then
 logEcho "[Korali] MPI not found. Installing Korali without support for MPI."
 logEcho "         > To use MPI, define the \$MPICXX environment variable."
 USE_MPI=0
else
 log "[Korali] Found $MPICXX for MPI compiler/wrapper."
 log "[Korali] Use 'export MPICXX=(path)' to use a different MPI wrapper."
 USE_CXX=$MPICXX
 MPIFLAGS="-D_KORALI_USE_MPI"
fi

######## Checking support for Python3 ########

log "[Korali] Checking for Python3 support using \"python3 --version\"."
pyver=`python3 --version`
if [ $? -eq 0 ]; then
  log "[Korali] Checking for python3-config."
  python3-config --help >> $logFile 2>&1
  if [ $? -ne 0 ]; then
    logEcho "[Korali] Error: python3-config not found."
    logEcho "[Korali] Solution: Please make sure the python3-dev package is correctly installed."
    exitWithError
  fi
else
  logEcho "[Korali] Error: Python3 not found."
  logEcho "[Korali] Solution: Please make sure the python3-config command is accesible in the PATH environment variable."
  exitWithError
fi
log "[Korali] Python3 version $pyver found."

######## Checking support for pip ########

log "[Korali] Checking for pip support using \"python3 -m pip --version\"..."
python3 -m pip --version >> $logFile 2>&1
if [ $? -ne 0 ]; then
  logEcho "[Korali] Error: pip not found among python3 packages."
  logEcho "[Korali] Solution: Make sure python3 and pip are correctly installed in your system."
  exitWithError
fi
# The --user flag should be set only if we are not inside a virtualenv.
PIP_USER=$(python3 -c "import sys; hasattr(sys, 'real_prefix') or print('--user')")

######## Checking support for Pybind11 ########

log "[Korali] Checking for Pybind11 support using \"python3 -m pybind11 -h\"..."
python3 -m pybind11 -h >> $logFile 2>&1
if [ $? -ne 0 ]; then

  if [ $INSTALLREQS -eq 0 ]; then
   logEcho "[Korali] Error: pybind11 not found, trying to install it automatically."
   logEcho "[Korali] Solution: Run \"./install\"."
   exitWithError
  fi
  
  logEcho "[Korali] pybind11 not found, trying to install it automatically."
  python3 -m pip install $PIP_USER pybind11 >> $logFile 2>&1; check
fi

######## Determining Library Flags ########

echo "[Korali] Creating configuration files..."

DNNLROOT=`readlink external/oneDNNlink`; check
ONEDNNCFLAGS="-D_KORALI_USE_ONEDNN -I${DNNLROOT}/include"
ONEDNNLIBS="-Wl,-rpath -Wl,${DNNLROOT}/lib64/ -L${DNNLROOT}/lib64/ -Wl,-rpath -Wl,${DNNLROOT}/lib/ -L${DNNLROOT}/lib/ -ldnnl"

LIBGPROOT=`readlink external/libGPlink`; check
LIBGPCFLAGS="-I${LIBGPROOT}/include"
LIBGPLIBS="-Wl,-rpath -Wl,${LIBGPROOT}/lib64/ -L${LIBGPROOT}/lib64/ -Wl,-rpath -Wl,${LIBGPROOT}/lib/ -L${LIBGPROOT}/lib/ -lgp"

LIBCOROOT=`readlink external/libcolink`; check
LIBCOCFLAGS="-I${LIBCOROOT}"
LIBCOLIBS="${LIBCOROOT}/libco.o"

EIGENROOT=`readlink external/eigenlink`; check
EIGENCFLAGS="-I${EIGENROOT}/include/eigen3"
 
GSLPREFIX=`./external/gsl-config --prefix`; check
GSLCFLAGS=`./external/gsl-config --cflags`; check
GSLLIBS=`./external/gsl-config --libs`; check
GSLLIBS="${GSLLIBS} -L${GSLPREFIX}/lib -Wl,-rpath -Wl,${GSLPREFIX}/lib"

PYBIND11INCLUDES=`python3 -m pybind11 --includes` ; check
PYBIND11LIBS=`python3-config --ldflags`; check

CXXARCH="-std=c++14"
which $USE_CXX | grep "cray" >> $logFile 2>&1
if [ $? -eq 0 ]; then
  logEcho "[Korali] Assuming Cray System."
  CC -craype-verbose 2>&1 | grep "driver.CC" >> $logFile 2>&1
  if [ $? -eq 0 ]; then
   logEcho "[Korali] Detected Cray compiler."
   CXXARCH="-hstd=c++14"
   PYBIND11LIBS=`echo $PYBIND11LIBS | sed 's/-Xlinker//g' | sed 's/-export-dynamic//g'`
  fi
fi

######## Checking selected compiler #######

if [[ "$USE_CXX" == "" ]]
then
  logEcho "[Korali] Error:  Did not found any valid C++ or MPI C++ compiler."
  logEcho "[Korali] Solution: Please define a valid C++ compiler in \$CXX or \$MPICXX."
  exitWithError
fi

######## Creating Compilation Config File ########

log "[Korali] Creating Compilation Config File..."

echo CXX=$USE_CXX > source/Makefile.conf
echo CXXARCH=$CXXARCH >> source/Makefile.conf
echo SHAREDLIB_FLAG=$SHAREDLIB_FLAG >> source/Makefile.conf
echo MPIFLAGS=$MPIFLAGS >> source/Makefile.conf

echo ONEDNNCFLAGS=$ONEDNNCFLAGS >> source/Makefile.conf
echo ONEDNNLIBS=$ONEDNNLIBS >> source/Makefile.conf

echo LIBGPCFLAGS=$LIBGPCFLAGS >> source/Makefile.conf
echo LIBGPLIBS=$LIBGPLIBS >> source/Makefile.conf

echo LIBCOCFLAGS=$LIBCOCFLAGS >> source/Makefile.conf
echo LIBCOLIBS=$LIBCOLIBS >> source/Makefile.conf

echo EIGENCFLAGS=$EIGENCFLAGS >> source/Makefile.conf
echo OPTFLAGS=$OPTFLAGS >> source/Makefile.conf
echo MACHINEARCH=$arch >> source/Makefile.conf

echo GSLPREFIX=$GSLPREFIX >> source/Makefile.conf
echo GSLCFLAGS=$GSLCFLAGS >> source/Makefile.conf
echo GSLLIBS=$GSLLIBS  >> source/Makefile.conf

echo PYBIND11INCLUDES=$PYBIND11INCLUDES >> source/Makefile.conf 
echo PYBIND11LIBS=$PYBIND11LIBS >> source/Makefile.conf

######## Compiling Korali C++ Engine #########

logEcho "[Korali] Building Korali Source..."
make -C source build >> $logFile 2>&1
if [ $? -ne 0 ]; then
  logEcho "[Korali] Error building Korali."
  exitWithError
fi

logEcho "[Korali] Compiling Korali..."
make -j$NJOBS -C source all >> $logFile 2>&1
if [ $? -ne 0 ]; then
  logEcho "[Korali] Error compiling Korali."
  exitWithError
fi

######## Installing Korali using pip ########

logEcho "[Korali] Installing Korali..."

cp source/libkorali.so . >> $logFile 2>&1
if [ $? -ne 0 ]; then
  logEcho "[Korali] Error obtaining libkorali.so"
  exitWithError
fi

python3 -m pip install . $PIP_USER --upgrade >> $logFile 2>&1
if [ $? -ne 0 ]; then
  logEcho "[Korali] Error installing Korali's Python module."
  exitWithError
fi

rm -f libkorali.so >> $logFile 2>&1 

echo "------------------------------------------------------------------"
echo "[Korali] Finished installation successfully."
echo "------------------------------------------------------------------"

