#!/usr/bin/env python3
import sys
sys.path.append('./model')
from directModel import *
import korali

import shutil
import os

if( os.path.exists("./_korali_result/") ) :
  shutil.rmtree("./_korali_result/")

k = korali.Engine()

k.setModel(evaluateModel)


k["Problem"] = "Direct Evaluation"

k["Solver"]  = "CMA-ES"

k["Variables"][0]["Name"] = "X";
k["Variables"][0]["CMA-ES"]["Lower Bound"] = -10.0;
k["Variables"][0]["CMA-ES"]["Upper Bound"] = +10.0;

k["CMA-ES"]["Objective"] = "Maximize"
k["CMA-ES"]["Termination Criteria"]["Max Generations"]["Value"] = 500
k["CMA-ES"]["Sample Count"] = 5



k.run()
