#!/usr/bin/env python3

## In this example, we demonstrate how Korali samples the posterior distribution
## in a bayesian problem where the likelihood is calculated by providing
## reference data points and their objective values.

# Importing the computational model
import sys
sys.path.append('./model')
from posteriorModel import *

# Getting reference data from the model
x, y = getReferenceData()

# Starting Korali's Engine
import korali
k = korali.initialize()

# Selecting problem and solver types.
k["Problem"] = "Bayesian"
k["Solver"] = "TMCMC";

# Setting up the reference likelihood for the Bayesian Problem
k["Bayesian"]["Likelihood"]["Type"] = "Reference"
k["Bayesian"]["Likelihood"]["Reference Data"] = y

# Configuring the problem's variables and their prior distributions
k["Variables"][0]["Name"] = "a"
k["Variables"][0]["Bayesian"]["Type"] = "Computational"
k["Variables"][0]["Bayesian"]["Prior Distribution"]["Type"] = "Uniform"
k["Variables"][0]["Bayesian"]["Prior Distribution"]["Minimum"] = -5.0
k["Variables"][0]["Bayesian"]["Prior Distribution"]["Maximum"] = +5.0

k["Variables"][1]["Name"] = "b"
k["Variables"][1]["Bayesian"]["Type"] = "Computational"
k["Variables"][1]["Bayesian"]["Prior Distribution"]["Type"] = "Uniform"
k["Variables"][1]["Bayesian"]["Prior Distribution"]["Minimum"] = -5.0
k["Variables"][1]["Bayesian"]["Prior Distribution"]["Maximum"] = +5.0

k["Variables"][2]["Name"] = "Sigma"
k["Variables"][2]["Bayesian"]["Type"] = "Statistical"
k["Variables"][2]["Bayesian"]["Prior Distribution"]["Type"] = "Uniform"
k["Variables"][2]["Bayesian"]["Prior Distribution"]["Minimum"] =   0.0
k["Variables"][2]["Bayesian"]["Prior Distribution"]["Maximum"] = +5.0

# Configuring TMCMC parameters
k["TMCMC"]["Covariance Scaling"] = 0.02;
k["TMCMC"]["Population Size"] = 5000;
k["TMCMC"]["Min Rho Update"] = 0.0;
k["TMCMC"]["Coefficient of Variation"] = 0.5;
k["TMCMC"]["Burn In"] = 5

# Setting model
k.setModel(lambda koraliData: evaluateModel(koraliData, x))

# Running Korali
k.run()