#!/usr/bin/env python3
import korali
import subprocess

def evaluate(x):
 argString = ['./model/ackley.py']
 for i in range(x.getVariableCount()):
  argString.append(str(x.getVariable(i)))
 retValue = subprocess.check_output(argString)
 x.addResult(float(retValue.decode()))

k = korali.Engine()
k["Verbosity"] = "Normal";

k["Problem"]["Type"] = "Direct";
for i in range(4):
    k["Problem"]["Variables"][i]["Name"] = "X" + str(i)
    k["Problem"]["Variables"][i]["Distribution"] = "Uniform"
    k["Problem"]["Variables"][i]["Type"] = "Computational"
    k["Problem"]["Variables"][i]["Minimum"] = -32.0
    k["Problem"]["Variables"][i]["Maximum"] = +32.0

k["Conduit"]["Type"] = "Nonintrusive"
k["Conduit"]["Concurrent Jobs"] = 16

k["Solver"]["Method"] = "CMA-ES"
k["Solver"]["Num Samples"] = 10
k["Solver"]["Termination Criteria"]["Max Generations"]["Value"] = 100
k["Solver"]["Termination Criteria"]["Min DeltaX"]["Value"] = 1e-12

k.setModel(evaluate)

k.run()
