#!/usr/bin/env python3
import korali
import subprocess

def evaluate(x):
  argString = ['./model/ackley.py']
  for i in range(x.getVariableCount()):
    argString.append(str(x.getVariable(i)))
  retValue = subprocess.check_output(argString)
  x.addResult(float(retValue.decode()))


k = korali.Engine()
k["Verbosity"] = "Normal";

k["Problem"]["Evaluation Type"] = "Direct";
for i in range(4):
  k["Problem"]["Variables"][i]["Name"] = "X" + str(i)

k["Conduit"]["Type"] = "Nonintrusive"
k["Conduit"]["Concurrent Jobs"] = 2

k["Solver"]["Method"] = "CMA-ES"
k["Solver"]["Sample Count"] = 10
for i in range(4):
  k["Solver"]["Variables"][i]["Lower Bound"] = -32.0;
  k["Solver"]["Variables"][i]["Upper Bound"] = +32.0;
k["Solver"]["Termination Criteria"]["Max Generations"]["Value"] = 100
k["Solver"]["Termination Criteria"]["Min DeltaX"]["Value"] = 1e-12

k.setModel(evaluate)

k.run()
