#!/usr/bin/env python3
import sys
sys.path.append('./model')
from ackley import m_ackley
import korali

k = korali.Engine()

k["Verbosity"] = "Normal";

k["Problem"]["Evaluation Type"] = "Direct";
for i in range(4):
 k["Problem"]["Variables"][i]["Name"] = "X" + str(i)
 k["Problem"]["Variables"][i]["Type"] = "Computational"
 k["Solver"]["Variables"][i]["Lower Bound"] = -32.0
 k["Solver"]["Variables"][i]["Upper Bound"] = +32.0

k["Solver"]["Method"] = "CMA-ES";
k["Solver"]["Sample Count"] = 10;
k["Solver"]["Termination Criteria"]["Max Generations"]["Value"] = 100;
k["Solver"]["Termination Criteria"]["Min DeltaX"]["Value"] = 1e-12;

k.setModel(m_ackley)

k.run()
